;  See https://tox.wiki/en
[tox]
requires =
    tox>=4
; run lint by default when just calling "tox"
env_list = lint

; ENVIRONMENTS
; ------------
[style]
description = common environment for style checkers (rely on pre-commit hooks)
skip_install = true
deps =
    pre-commit

; COMMANDS
; --------
[testenv:lint]
description = run all linters and formatters
skip_install = true
deps =
    {[style]deps}
commands =
	pre-commit run --all-files --show-diff-on-failure {posargs:}

[testenv:flake8]
description = run flake8
skip_install = true
deps =
    {[style]deps}
commands =
    pre-commit run --all-files --show-diff-on-failure flake8

; COMMANDS
; --------
[testenv:test_notebooks]
description = execute the release-critical tutorial notebooks
extras = test
deps =
    nbformat
    nbclient
    jupyter
commands =
    python -m validation.execute_notebooks --output-dir validation/_artifacts/tox_notebooks

[testenv:docs]
description = build the documentation
extras = doc
setenv =
    NEURODESIGN_DOCS_OFFLINE = 1
commands =
    python -m sphinx -W --keep-going -b html docs docs/_build/html_ci


[testenv:tests]
description = run tests on latest version of all dependencies
extras = test
commands =
    pytest --cov=neurodesign --cov-report=xml tests {posargs:}
